source 'https://rubygems.org'
ruby '2.6.3'

gem 'sidekiq'
gem 'sidekiq-failures', '~> 1.0'
gem 'pg_search'
gem 'authtrail'
gem 'turbolinks', '~> 5.2.0'
gem 'chartkick'
gem 'nokogiri'
gem 'ffi'
gem 'groupdate', '~> 4.1'
gem 'fusioncharts-rails'
gem 'highcharts-rails'
gem 'acts_as_votable', '~> 0.11.1'
gem 'jquery-rails'
gem 'sidekiq'
gem 'sidekiq-status'
gem 'sidekiq-failures', '~> 1.0'
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'pg', '~> 1.0'
gem 'puma'
gem 'rails', '5.1.6'
gem 'redis'

gem 'autoprefixer-rails'
gem 'bootstrap-sass', '~> 3.3'
gem 'font-awesome-sass', '~> 5.0.9'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker', '~> 4.0.0'

group :development do
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
